# Generated by Django 5.2.3 on 2025-06-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_ordered_at_order_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Plate', 'Plate'), ('Spoon', 'Spoon'), ('Fork', 'Fork'), ('Bowl', 'Bowl'), ('Cup', 'Cup'), ('Knife', 'Knife')], max_length=10),
        ),
    ]
