services:
  - type: web
    name: areca-shop-web
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn areca_shop.wsgi
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: areca-shop-db
          property: connectionString
      - key: DJANGO_ALLOWED_HOSTS
        value: areca-shop-project.onrender.com  # Update to your real render subdomain

databases:
  - name: areca-shop-db
    databaseName: areca_shop_db
    user: root
